#!/usr/bin/env node
'use strict';

/**
 * OpenAPI Normalizer
 *
 * Cleans and normalizes Postman-exported OpenAPI 3.x JSON:
 *   - Strips noisy HTTP transport response headers (CORS, security headers, etc.)
 *   - Collapses named `examples` → single `example`, keeps existing `schema`
 *   - Merges multiple response example payloads into one unified schema when
 *     no schema exists yet (schema inference)
 *   - Removes empty `security: [{}]` entries
 *   - Removes `description` when it duplicates `summary`
 *   - Removes empty `contact`, `components.securitySchemes`, etc.
 *   - Deduplicates the global `tags` array
 *   - Annotates Postman `{{VARIABLE}}` server URLs with a description
 *
 * Usage:
 *   node normalizer.js <input.json> [output.json]
 *   node normalizer.js openapi-example.json               # writes openapi-example.normalized.json
 *   node normalizer.js openapi-example.json clean.json   # writes clean.json
 */

const fs = require('fs');

// ---------------------------------------------------------------------------
// HTTP headers generated by Postman that carry no API contract meaning
// ---------------------------------------------------------------------------
const NOISY_HEADERS = new Set([
  'Access-Control-Allow-Headers',
  'Access-Control-Allow-Methods',
  'Access-Control-Allow-Origin',
  'Access-Control-Expose-Headers',
  'Access-Control-Max-Age',
  'Connection',
  'Content-Encoding',
  'Content-Length',
  'Content-Security-Policy',
  'Cross-Origin-Embedder-Policy',
  'Cross-Origin-Opener-Policy',
  'Cross-Origin-Resource-Policy',
  'Date',
  'ETag',
  'Keep-Alive',
  'Origin-Agent-Cluster',
  'Referrer-Policy',
  'Server',
  'Set-Cookie',
  'Strict-Transport-Security',
  'Transfer-Encoding',
  'Vary',
  'X-Content-Type-Options',
  'X-DNS-Prefetch-Control',
  'X-Download-Options',
  'X-Frame-Options',
  'X-Permitted-Cross-Domain-Policies',
  'X-XSS-Protection',
  // Postman often captures these as response headers
  'authorization',
  'Authorization',
  'x-request-id',
  'X-Request-Id',
]);

// ---------------------------------------------------------------------------
// Schema inference from a runtime JSON value
// ---------------------------------------------------------------------------
function inferSchema(value) {
  if (value === null) return { nullable: true };
  if (Array.isArray(value)) {
    if (value.length === 0) return { type: 'array', items: {} };
    const itemSchemas = value.map(inferSchema);
    return { type: 'array', items: mergeSchemas(itemSchemas) };
  }
  if (typeof value === 'object') {
    const properties = {};
    for (const [k, v] of Object.entries(value)) {
      properties[k] = inferSchema(v);
    }
    return { type: 'object', properties };
  }
  if (typeof value === 'string') return { type: 'string', example: value };
  if (typeof value === 'number') {
    return Number.isInteger(value)
      ? { type: 'integer', example: value }
      : { type: 'number', example: value };
  }
  if (typeof value === 'boolean') return { type: 'boolean', example: value };
  return {};
}

/**
 * Deeply merge an array of JSON Schema objects into one representative schema.
 * Objects → union of properties; arrays → merged items; mixed types → oneOf.
 */
function mergeSchemas(schemas) {
  schemas = schemas.filter((s) => s && Object.keys(s).length > 0);
  if (schemas.length === 0) return {};
  if (schemas.length === 1) return schemas[0];

  const types = [...new Set(schemas.map((s) => s.type).filter(Boolean))];

  if (types.length === 1 && types[0] === 'object') {
    const allProps = {};
    for (const schema of schemas) {
      for (const [k, v] of Object.entries(schema.properties || {})) {
        allProps[k] = allProps[k] ? mergeSchemas([allProps[k], v]) : v;
      }
    }
    return { type: 'object', properties: allProps };
  }

  if (types.length === 1 && types[0] === 'array') {
    const itemSchemas = schemas.map((s) => s.items).filter(Boolean);
    return { type: 'array', items: mergeSchemas(itemSchemas) };
  }

  if (types.length === 0) {
    // All nullable or unknown – just return first
    return schemas[0];
  }

  // Genuinely mixed types: use oneOf
  return { oneOf: schemas };
}

// ---------------------------------------------------------------------------
// Parse an example value that may be a raw JSON string or already an object
// ---------------------------------------------------------------------------
function parseExampleValue(val) {
  if (typeof val === 'string') {
    try {
      return JSON.parse(val);
    } catch {
      return val;
    }
  }
  return val;
}

// ---------------------------------------------------------------------------
// Strip `example` values from schema property definitions recursively.
// A top-level `example` on the media object itself is kept; per-property
// examples are redundant noise when the whole response example is present.
// ---------------------------------------------------------------------------
function stripPropertyExamples(schema) {
  if (!schema || typeof schema !== 'object') return schema;
  if (Array.isArray(schema)) return schema.map(stripPropertyExamples);

  const result = {};
  for (const [k, v] of Object.entries(schema)) {
    if (k === 'example') continue; // drop inline property examples
    if (k === 'properties' && v && typeof v === 'object') {
      const cleanedProps = {};
      for (const [propName, propSchema] of Object.entries(v)) {
        cleanedProps[propName] = stripPropertyExamples(propSchema);
      }
      result[k] = cleanedProps;
    } else if (k === 'items' || k === 'additionalProperties') {
      result[k] = stripPropertyExamples(v);
    } else if (k === 'oneOf' || k === 'anyOf' || k === 'allOf') {
      result[k] = v.map(stripPropertyExamples);
    } else {
      result[k] = v;
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// Normalize a single media-type object (inside request/response content)
//
//  Rules:
//   1. If there is a proper schema already, keep it; just collapse examples.
//   2. If the schema is missing or empty AND there are named examples, infer
//      a schema by merging all example values.
//   3. Collapse the named `examples` map to a single top-level `example`
//      by picking the first entry.
//   4. Remove the `examples` map.
//   5. Strip per-property `example` values from the schema (redundant).
// ---------------------------------------------------------------------------
function normalizeMediaTypeObject(mediaObj) {
  const result = { ...mediaObj };
  const hasExamples =
    result.examples && Object.keys(result.examples).length > 0;

  if (hasExamples) {
    const exampleEntries = Object.values(result.examples);
    const parsedValues = exampleEntries
      .map((ex) => parseExampleValue(ex.value))
      .filter((v) => v !== undefined && v !== null);

    const schemaIsEmpty =
      !result.schema || Object.keys(result.schema).length === 0;

    // Infer schema only when one doesn't already exist
    if (schemaIsEmpty && parsedValues.length > 0) {
      const inferred = mergeSchemas(parsedValues.map(inferSchema));
      if (Object.keys(inferred).length > 0) {
        result.schema = inferred;
      }
    }

    // Pick the first example as the representative top-level example
    const firstParsed = parsedValues[0];
    if (firstParsed !== undefined) {
      result.example = firstParsed;
    }

    delete result.examples;
  }

  // Drop an empty schema object
  if (result.schema && Object.keys(result.schema).length === 0) {
    delete result.schema;
  }

  // Strip per-property example values — redundant when a top-level example exists
  if (result.schema) {
    result.schema = stripPropertyExamples(result.schema);
  }

  return result;
}

// ---------------------------------------------------------------------------
// Normalize content map (e.g. { "application/json": { schema, examples } })
// ---------------------------------------------------------------------------
function normalizeContent(content) {
  if (!content) return content;
  const result = {};
  for (const [mediaType, mediaObj] of Object.entries(content)) {
    result[mediaType] = normalizeMediaTypeObject(mediaObj);
  }
  return result;
}

// ---------------------------------------------------------------------------
// Strip noisy transport-level response headers; keep only meaningful ones
// ---------------------------------------------------------------------------
function stripNoisyHeaders(headers) {
  if (!headers) return undefined;
  const cleaned = {};
  for (const [name, headerObj] of Object.entries(headers)) {
    if (!NOISY_HEADERS.has(name)) {
      cleaned[name] = headerObj;
    }
  }
  return Object.keys(cleaned).length > 0 ? cleaned : undefined;
}

// ---------------------------------------------------------------------------
// Normalize a single response object
// ---------------------------------------------------------------------------
function normalizeResponse(response) {
  const result = { description: response.description ?? '' };

  const headers = stripNoisyHeaders(response.headers);
  if (headers) result.headers = headers;

  if (response.content) {
    result.content = normalizeContent(response.content);
  }

  return result;
}

// ---------------------------------------------------------------------------
// Normalize a single operation object (get/post/put/…)
// ---------------------------------------------------------------------------
function normalizeOperation(operation) {
  const result = { ...operation };

  // Remove description when it's a verbatim copy of the summary
  if (
    result.description &&
    result.summary &&
    result.description.trim() === result.summary.trim()
  ) {
    delete result.description;
  }

  // Remove security: [{}]  –  empty security requirement objects mean nothing
  if (Array.isArray(result.security)) {
    const meaningful = result.security.filter(
      (s) => s && Object.keys(s).length > 0,
    );
    if (meaningful.length === 0) delete result.security;
    else result.security = meaningful;
  }

  // Normalize request body content
  if (result.requestBody?.content) {
    result.requestBody = {
      ...result.requestBody,
      content: normalizeContent(result.requestBody.content),
    };
  }

  // Normalize responses
  if (result.responses) {
    const normalizedResponses = {};
    for (const [code, response] of Object.entries(result.responses)) {
      normalizedResponses[code] = normalizeResponse(response);
    }
    result.responses = normalizedResponses;
  }

  return result;
}

// ---------------------------------------------------------------------------
// Normalize all paths
// ---------------------------------------------------------------------------
const HTTP_METHODS = [
  'get',
  'put',
  'post',
  'delete',
  'options',
  'head',
  'patch',
  'trace',
];

function normalizePaths(paths) {
  if (!paths) return paths;
  const result = {};
  for (const [pathStr, pathItem] of Object.entries(paths)) {
    const normalizedItem = { ...pathItem };
    for (const method of HTTP_METHODS) {
      if (normalizedItem[method]) {
        normalizedItem[method] = normalizeOperation(normalizedItem[method]);
      }
    }
    result[pathStr] = normalizedItem;
  }
  return result;
}

// ---------------------------------------------------------------------------
// Deduplicate the global tags array (last one with a description wins)
// ---------------------------------------------------------------------------
function normalizeTags(tags) {
  if (!Array.isArray(tags)) return tags;
  const seen = new Map();
  for (const tag of tags) {
    const existing = seen.get(tag.name);
    if (!existing || tag.description) {
      seen.set(tag.name, tag);
    }
  }
  return [...seen.values()];
}

// ---------------------------------------------------------------------------
// Annotate Postman {{VARIABLE}} server URLs
// ---------------------------------------------------------------------------
function normalizeServers(servers) {
  if (!Array.isArray(servers)) return servers;
  return servers.map((server) => {
    const match = server.url && server.url.match(/^\{\{(.+)\}\}$/);
    if (match) {
      return {
        url: '/', // placeholder; replace before deployment
        description: `${match[1]} — set this URL in your environment`,
        'x-postman-variable': server.url,
      };
    }
    return server;
  });
}

// ---------------------------------------------------------------------------
// Normalize the info object
// ---------------------------------------------------------------------------
function normalizeInfo(info) {
  if (!info) return info;
  const result = { ...info };
  // Remove empty contact object
  if (result.contact && Object.keys(result.contact).length === 0) {
    delete result.contact;
  }
  return result;
}

// ---------------------------------------------------------------------------
// Normalize components
// ---------------------------------------------------------------------------
function normalizeComponents(components) {
  if (!components) return undefined;
  const result = { ...components };

  if (
    result.securitySchemes &&
    Object.keys(result.securitySchemes).length === 0
  ) {
    delete result.securitySchemes;
  }

  return Object.keys(result).length > 0 ? result : undefined;
}

// ---------------------------------------------------------------------------
// Top-level normalize function
// ---------------------------------------------------------------------------
function normalize(openapi) {
  const result = { ...openapi };

  if (result.info) result.info = normalizeInfo(result.info);
  if (result.servers) result.servers = normalizeServers(result.servers);
  if (result.paths) result.paths = normalizePaths(result.paths);
  if (result.tags) result.tags = normalizeTags(result.tags);

  const components = normalizeComponents(result.components);
  if (components) result.components = components;
  else delete result.components;

  return result;
}

// ---------------------------------------------------------------------------
// Stats helper
// ---------------------------------------------------------------------------
function sizeKB(str) {
  return (Buffer.byteLength(str, 'utf-8') / 1024).toFixed(1);
}

function reductionPct(before, after) {
  return (((before - after) / before) * 100).toFixed(1);
}

// ---------------------------------------------------------------------------
// CLI entrypoint
// ---------------------------------------------------------------------------
const args = process.argv.slice(2);

if (args.length === 0) {
  console.error(
    'Usage: node normalizer.js <input.json> [output.json]\n' +
      '       node normalizer.js openapi-example.json\n' +
      '       node normalizer.js openapi-example.json clean.json',
  );
  process.exit(1);
}

const inputFile = args[0];
const outputFile =
  args[1] || inputFile.replace(/(\.[^.]+)$/, '.normalized$1');

let raw;
try {
  raw = fs.readFileSync(inputFile, 'utf-8');
} catch (err) {
  console.error(`Cannot read "${inputFile}": ${err.message}`);
  process.exit(1);
}

let openapi;
try {
  openapi = JSON.parse(raw);
} catch (err) {
  console.error(`Invalid JSON in "${inputFile}": ${err.message}`);
  process.exit(1);
}

const normalized = normalize(openapi);
const outputRaw = JSON.stringify(normalized, null, 2);

try {
  fs.writeFileSync(outputFile, outputRaw);
} catch (err) {
  console.error(`Cannot write "${outputFile}": ${err.message}`);
  process.exit(1);
}

const inputBytes = Buffer.byteLength(raw, 'utf-8');
const outputBytes = Buffer.byteLength(outputRaw, 'utf-8');

console.log(`OpenAPI Normalizer`);
console.log(`  Input  : ${inputFile} (${sizeKB(raw)} KB)`);
console.log(`  Output : ${outputFile} (${sizeKB(outputRaw)} KB)`);
console.log(
  `  Saved  : ${(((inputBytes - outputBytes) / inputBytes) * 100).toFixed(1)}% (${((inputBytes - outputBytes) / 1024).toFixed(1)} KB)`,
);
console.log(`Done.`);
